name: "[Deployment] webservice"
on:
  push:
    branches: [master, deployment/production]
  pull_request:
    branches: [master, deployment/production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -f apps/webservice/Dockerfile -t registry.agrid.ml/agrid-webservice:$GITHUB_SHA -t registry.agrid.ml/agrid-webservice:latest .
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.agrid.ml -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: docker push
        run: docker push registry.agrid.ml/agrid-webservice --all-tags
