name: "[Deployment] webapp"
on:
  push:
    branches: [master, deployment/production]
  pull_request:
    branches: [master, deployment/production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login https://registry.agrid.ml/v2 -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      # - name: docker build
      #   run: docker build -t :latest .
      # - name: Tag the Docker image
      #   run: docker tag myimage:latest myimage:1.0
      # - name: Push the Docker image to the registry
      #   run: docker push myimage:1.0
