name: '[Deployment] webapp'
on:
  push:
    branches: [deployment/production]
  pull_request:
    branches: [deployment/production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -f apps/webapp/Dockerfile -t registry.agrid.ml/agrid-webapp:$GITHUB_SHA -t registry.agrid.ml/agrid-webapp:latest .
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.agrid.ml -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: docker push
        run: docker push registry.agrid.ml/agrid-webapp --all-tags
